// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkFinder.Models;

namespace ParkFinder.Migrations
{
    [DbContext(typeof(ParkFinderContext))]
    partial class ParkFinderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkFinder.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area");

                    b.Property<string>("DateEstablished");

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Area = "47,389.67 acres (191.8 km2)",
                            DateEstablished = "January 1, 2010",
                            Description = "Set in Downtown Portland, this park feature lots of computers, feral young programmers, and hand sanitizer.",
                            Location = "Portland, OR",
                            Name = "Epicodus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
